-- Q1. Total Revenue generated by Male vs female customers ? 
SELECT Gender , SUM(`Purchase Amount (USD)`) AS revenue
FROM customer 
GROUP BY  Gender



-- Q2. which customer used  a discount but still spend more then avg purchase amount ?
SELECT `Customer ID`, `Purchase Amount (USD)` FROM customer
WHERE `Discount Applied` = 'Yes' AND `Purchase Amount (USD)` >= (SELECT AVG(`Purchase Amount (USD)`)FROM customer);



-- Q3 Top 5  Product with highet avg review rating
SELECT `Item Purchased`, ROUND(AVG(`Review Rating`),2) AS "Average Product Rating" 
FROM customer
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;





 -- Q4 compare avg purchased amount between standard and express shipping
 SELECT `Shipping Type`,
 ROUND(AVG(`Purchase Amount (USD)`),2)
FROM customer
WHERE `Shipping Type` IN ('Standard','Express')
GROUP BY `Shipping Type`




-- Q5 Do subscribed customers spend more? compare avg spend and total revenue between subscriber and non-subscriber
SELECT `Subscription Status`,
COUNT(`Customer ID`) AS Total_customers,
ROUND(AVG(`Purchase Amount (USD)`),2) AS Average_Spend,
ROUND(SUM(`Purchase Amount (USD)`),2) AS Total_Revenue
FROM customer
GROUP BY `Subscription Status`
ORDER BY Total_Revenue,
Average_Spend DESC;





-- Q6 Which 5 Product have the highest Percentages of purchases with  Discount Applied
SELECT `Item Purchased`,
ROUND(SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END ) / COUNT(*) * 100.0,2) AS Discount_Rate
FROM customer
GROUP BY `Item Purchased`
ORDER BY Discount_Rate DESC
LIMIT 5; 





-- Q7. Segment customers into new,returning and loyal based on their total number of previous purchases and show the count of each segment
WITH customer_type AS (
SELECT `Customer ID`,`Previous Purchases`,
CASE 
WHEN `Previous Purchases` = 1 THEN 'New'
WHEN `Previous Purchases` BETWEEN  2  AND 10 THEN 'Return'
ElSE 'Loyal'
 END AS customer_segment
 FROM customer
 )
 SELECT customer_segment,COUNT(*) AS 'Number of Customers'
 FROM customer_type 
 GROUP BY customer_segment



-- Q8. What are the top 3 most purchased product in each category?
WITH item_count AS (
SELECT `Category`,
`Item Purchased`,
COUNT(`Customer ID`) AS total_order,
ROW_NUMBER() OVER( PARTITION BY `Category` ORDER BY COUNT(`Customer ID`)DESC) AS Item_Rank 
FROM customer
GROUP BY `Category`,`Item Purchased`
)
SELECT Item_Rank,`Category`,`Item Purchased`,total_order
FROM item_count
WHERE Item_Rank <= 3;




-- Q9. Are customers who are repeat buyers (more then 5  previous  purchases) also likely to sbuscribe?
SELECT `Subscription Status`,
COUNT(`Customer ID`) AS repeat_buyers
FROM customer
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;



-- Q10. What is the revenue contribution for eacg age group?

SELECT 
CASE 
WHEN `Age` < 18 THEN 'Teenager'  
WHEN `Age` BETWEEN 18 AND 30 THEN 'Young Adult' 
WHEN `Age` BETWEEN 31 AND 50 THEN 'Middle Age'
ELSE 'senior'
END AS Age_group,
SUM(`Purchase Amount (USD)`) AS total_Revenue
FROM customer
GROUP BY Age_group
ORDER BY total_Revenue DESC;





